### ISSUE TITLE
Connect error

### ISSUE THREAD

**Issue by ghost** [yeasy/docker-blockchain-explorer#1]
When I run the command "docker run -p 9090:9090 -e HYP_REST_ENDPOINT=http://127.0.0.1:7050 yeasy/blockchain-explorer",  I get the following error.  

> Compiling all doT templates...
Compiling HyperlegerExplorer.jst to file
{ Error: connect ECONNREFUSED 127.0.0.1:7050
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 7050 }

And, "docker ps" result on my machine:
> CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                              NAMES
8009a7b7f478        dev-peer3-mycc-1.0           "chaincode -peer.addr"   About an hour ago   Up About an hour                                                       dev-peer3-mycc-1.0
e4672f2a9477        dev-peer0-mycc-1.0           "chaincode -peer.addr"   About an hour ago   Up About an hour                                                       dev-peer0-mycc-1.0
7a1845e28a24        dev-peer2-mycc-1.0           "chaincode -peer.addr"   About an hour ago   Up About an hour                                                       dev-peer2-mycc-1.0
6bea7a7f22c6        hyperledger/fabric-peer      "peer node start --pe"   About an hour ago   Up About an hour    0.0.0.0:10051->7051/tcp, 0.0.0.0:10053->7053/tcp   peer3
dc31cb3220e8        hyperledger/fabric-peer      "peer node start --pe"   About an hour ago   Up About an hour    0.0.0.0:9051->7051/tcp, 0.0.0.0:9053->7053/tcp     peer2
93f977c33b6a        hyperledger/fabric-peer      "peer node start --pe"   About an hour ago   Up About an hour    0.0.0.0:8051->7051/tcp, 0.0.0.0:8053->7053/tcp     peer1
e65f7eb55078        hyperledger/fabric-peer      "peer node start --pe"   About an hour ago   Up About an hour    0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp     peer0
ce001ce2f115        hyperledger/fabric-orderer   "orderer"                About an hour ago   Up About an hour    0.0.0.0:7050->7050/tcp                             orderer0

Also, I can telnet "127.0.0.1 7050".
Please tell me what can result in this error.

**Comment by yeasy** [comment]
the explorer only supports v0.6 now.
