### ISSUE TITLE
Explorer for Hyperledger Fabric 1.0 

### ISSUE THREAD

**Issue by leonli-github** [yeasy/docker-blockchain-explorer#3]
Hi yeasy,
    First, thank you for your great work. 
    Here I am trying to connect explore to Hyperledger Fabric 1.0. But according to https://github.com/yeasy/docker-compose-files/issues/12. You mentioned rest api is not supported in Fabric 1.0. 
    Does it mean I cannot use blockchain explorer on Fabric 1.0 network?
    Again, thanks a lot.
Regards,
Leon

**Comment by yeasy** [comment]
No, you cannot use it with fabric 1.0 till now.

Sorry for the potential inconvenience.

**Comment by rahianeja** [comment]
I think head over to https://hyperledger.github.io/composer/index.html for creating blockchain apps and network.

There is also a support for creation of REST services for web apps
