### ISSUE TITLE
Docker run with /HyperLedger/0.6/pbft error

### ISSUE THREAD

**Issue by yangboz** [yeasy/docker-blockchain-explorer#5]
While 
"docker-compose -f 4-peers-with-membersrvc.yml up -d" 

then

 " docker run -p 9090:9090 -e HYP_REST_ENDPOINT=http://127.0.0.1:7050 yeasy/blockchain-explorer"

It was thrown:

"
Compiling HyperlegerExplorer.jst to file
{ Error: connect ECONNREFUSED 127.0.0.1:7050
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 7050 }
"

Any version number mismatch? & thanks.

**Comment by yeasy** [comment]
We haven't test BE with fabric 1.0 yet.
Welcome to feedback it you have them work together.
Thanks!

**Comment by yangboz** [comment]
So which version that explorer matched and workable? thanks.

**Comment by yeasy** [comment]
v0.6 BE image works with fabric v0.6.x.
master branch is with latest BE code.

**Comment by yangboz** [comment]
Actually, 

 before "RUN git clone https://github.com/hyperledger/blockchain-explorer"

 there is no "WORKDIR /blockchain-explorer/explorer_1", it only has "explorer_client" directory.

**Comment by yeasy** [comment]
Correct, we are migrating to support fabric 1.0, while it's not done yet.

**Comment by ghost** [comment]
@yangboz I'm working on user dashboard in cello, this feature will be released at the end of December 2017, then you can apply chain, initial chain, query block, transaction, invoke transaction, and publish smart contract in the user dashboard, and more feature.
